Feature/issue 7 - Remove wait for GITC response
podaac/bignbit pull request #30
Opened 2024-06-05 00:51 UTC by torimcd

Github Issue: closes #7 

### Description

Waiting for the GITC response currently throttles the number of image sets we can send. Change to remove the wait period and complete successfully when we complete the send. Handle the GITC response outside of the state machine.

### Overview of work done

- remove the wait for task token during the sendToGITC lambda
- change to using the image name + granule concept id for the CNM identifier
- save CNM message sent to GITC in audit bucket with granuleUR + submission time as filename
- move the umm-json lookup to the utils module so it can be reused out of state machine
- handle the GITC response separately by moving to a regular lambda (not a cumulus process) and save the CNM-R in the same audit location with same filename (+cnm-r.json) to enable easy reconciliation

### Overview of verification done

No new unit tests, existing tests pass

### Overview of integration done

Deployed to SIT. Workflow succeeds when invoked manually and both CNM & CNM-R messages are saved in the audit bucket under collection_var prefix

## PR checklist:

* [x] Linted
* [x] Updated unit tests
* [x] Updated changelog
* [x] Integration testing

_See [Pull Request Review Checklist](../CONTRIBUTING.md#reviewing) for pointers on reviewing this pull request_

2024-06-05 01:40 UTC, frankinspace requested changes
This looks great, just a few comments.

2024-06-05 01:40 UTC, frankinspace commented on bignbit/handle_gitc_response.py
> +        granule_concept_id = gitc_id[-19:]
Will this be consistent? I think a delimited id would be better than positional because afaik concept id's are not fixed length strings

2024-06-05 01:40 UTC, frankinspace commented on terraform/lambda_functions.tf
> +      EDL_PASS_SSM                = var.edl_pass_ssm
Does send_to_gitc require EDL? Looks like it doesn't

2024-06-05 01:40 UTC, frankinspace commented on bignbit/save_cma_message.py
This function is no longer used, correct? I think it can be removed

2024-06-05 16:08 UTC, torimcd commented on bignbit/save_cma_message.py
done

2024-06-05 16:08 UTC, torimcd commented on terraform/lambda_functions.tf
> +      EDL_PASS_SSM                = var.edl_pass_ssm
good catch, removed

2024-06-05 16:09 UTC, torimcd commented on bignbit/handle_gitc_response.py
> +        granule_concept_id = gitc_id[-19:]
great point, changed to parse based on the last '_' in the string now

2024-06-17 17:22 UTC, frankinspace approved these changes

2024-06-17 17:23 UTC, merged